# Generated by Django 4.2.23 on 2025-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession', models.TextField(blank=True, null=True, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('article_count', models.IntegerField(default=0, verbose_name='Кол-во статей')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkedIn')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('image', models.ImageField(blank=True, upload_to='authors/', verbose_name='Фото автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
