# Generated by Django 4.2.23 on 2025-08-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='article_count',
        ),
    ]
