# Generated by Django 5.2.13 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_author_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_kz',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='author',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='description_kz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='author',
            name='profession_en',
            field=models.TextField(blank=True, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='author',
            name='profession_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='author',
            name='profession_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_kz',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
    ]
