# Generated by Django 3.2 on 2023-07-03 06:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.JSONField(default=dict, verbose_name='Картинки')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Заголовок')),
                ('alias', models.CharField(blank=True, db_index=True, max_length=1000, null=True, unique=True, verbose_name='Алиас')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Лид')),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('changed_user', models.JSONField(default=dict, verbose_name='Внесший изменения')),
                ('author', models.UUIDField(blank=True, null=True, verbose_name='Автор')),
                ('pseudonym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Псевдоним')),
                ('view_count', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('locked', models.BooleanField(default=False)),
                ('lock_time', models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки')),
                ('editor', models.UUIDField(blank=True, null=True, verbose_name='Редактирует')),
                ('article_type', models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=2, null=True, verbose_name='Тип новости')),
                ('article_status', models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус новости')),
                ('public_params', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Лента'), (2, 'Выделить в лента'), (3, 'Главная'), (4, 'Пресс-релизы'), (5, 'Без категории')]), blank=True, default=list, null=True, size=None)),
                ('public_types', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Фото'), (2, 'Видео'), (3, 'Инфографика'), (4, 'Эксклюзив'), (5, '18+')]), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('seo_text', models.CharField(max_length=250, verbose_name='СЕО заголовок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Лид')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('created_user', models.CharField(blank=True, max_length=250, verbose_name='Пользователь')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='news.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='FixedMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('order', models.IntegerField(unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Лид')),
                ('seo_tag', models.CharField(max_length=80, null=True, verbose_name='Описание для сео')),
                ('tag_name', models.CharField(blank=True, max_length=250, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('index_level', models.IntegerField(default=0, verbose_name='Индекс')),
                ('created_user', models.CharField(blank=True, max_length=250, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='FixedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_news', to='news.article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='Заголовок')),
                ('alias', models.CharField(blank=True, db_index=True, max_length=1000, null=True, unique=True, verbose_name='Алиас')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Лид')),
                ('content', models.TextField()),
                ('author', models.UUIDField(blank=True, null=True, verbose_name='Автор')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('categories', models.ManyToManyField(blank=True, related_name='category_draft_article', to='news.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_draft_article', to='news.Tag')),
            ],
            options={
                'verbose_name': 'Draft Article',
                'verbose_name_plural': 'Draft Articles',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_article', to='news.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_article', to='news.Tag'),
        ),
    ]
