# Generated by Django 3.2 on 2025-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftarticle',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Картинки'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='request_url',
            field=models.TextField(blank=True, null=True, verbose_name='Базовый URL'),
        ),
    ]
