# Generated by Django 3.2 on 2025-05-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20250424_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='changed_user',
        ),
    ]
