# Generated by Django 3.2 on 2025-05-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_changed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('use_case', models.CharField(max_length=255)),
                ('checkpoints', models.JSONField()),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('safety_management', 'Safety management'), ('training_registers', 'Реестры по обучению'), ('incidents', 'Инциденты и расследования'), ('other', 'Другие документы')], max_length=50)),
                ('topics', models.CharField(blank=True, max_length=255)),
                ('file_url', models.URLField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('law', 'Закон'), ('code', 'Кодекс'), ('npa', 'НПА'), ('gost', 'ГОСТ')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('date_of_issue', models.DateField()),
                ('relevance_status', models.CharField(choices=[('actual', 'Актуален'), ('obsolete', 'Устарел')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('speakers', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Прошёл'), ('recording', 'Запись')], max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction_type', models.CharField(choices=[('introductory', 'Вводный'), ('primary', 'Первичный'), ('repeated', 'Повторный'), ('targeted', 'Целевой'), ('unscheduled', 'Внеплановый')], max_length=50)),
                ('format', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('pdf', 'PDF')], max_length=20)),
                ('categories', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('related_checklists', models.ManyToManyField(blank=True, related_name='instructions', to='news.Checklist')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='instructions', to='news.Document')),
            ],
        ),
    ]
