# Generated by Django 3.2 on 2025-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_checklist_document_faq_instruction_legalact_webinar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чек-лист', 'verbose_name_plural': 'Чек-листы'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': 'Инструктаж', 'verbose_name_plural': 'Инструктажи'},
        ),
        migrations.AlterModelOptions(
            name='legalact',
            options={'verbose_name': 'Нормативный акт', 'verbose_name_plural': 'Нормативные акты'},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={'verbose_name': 'Вебинар', 'verbose_name_plural': 'Вебинары'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checkpoints',
            field=models.JSONField(verbose_name='Пункты проверки'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='use_case',
            field=models.CharField(max_length=255, verbose_name='Сценарий использования'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('safety_management', 'Safety management'), ('training_registers', 'Реестры по обучению'), ('incidents', 'Инциденты и расследования'), ('other', 'Другие документы')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topics',
            field=models.CharField(blank=True, max_length=255, verbose_name='Темы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='valid_from',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='valid_to',
            field=models.DateField(verbose_name='Дата окончания действия'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='categories',
            field=models.CharField(max_length=255, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Встроенный текст'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='format',
            field=models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('pdf', 'PDF')], max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_type',
            field=models.CharField(choices=[('introductory', 'Вводный'), ('primary', 'Первичный'), ('repeated', 'Повторный'), ('targeted', 'Целевой'), ('unscheduled', 'Внеплановый')], max_length=50, verbose_name='Тип инструктажа'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='related_checklists',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='news.Checklist', verbose_name='Связанные чек-листы'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='related_documents',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='news.Document', verbose_name='Связанные документы'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название инструктажа'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='relevance_status',
            field=models.CharField(choices=[('actual', 'Актуален'), ('obsolete', 'Устарел')], max_length=20, verbose_name='Статус актуальности'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='type',
            field=models.CharField(choices=[('law', 'Закон'), ('code', 'Кодекс'), ('npa', 'НПА'), ('gost', 'ГОСТ')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='speakers',
            field=models.CharField(max_length=255, verbose_name='Спикеры'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Прошёл'), ('recording', 'Запись')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
