# Generated by Django 3.2 on 2025-05-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20250528_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
