# Generated by Django 3.2 on 2025-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20250528_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='file_url',
        ),
        migrations.AddField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
