# Generated by Django 3.2 on 2025-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20250529_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
