# Generated by Django 3.2 on 2025-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_instruction_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
