# Generated by Django 3.2 on 2025-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20250529_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='categories',
        ),
        migrations.AddField(
            model_name='instruction',
            name='category',
            field=models.CharField(choices=[('introductory', 'Вводный инструктаж'), ('primary_workplace', 'Первичный на рабочем месте'), ('repeated', 'Повторный'), ('unscheduled', 'Внеплановый'), ('targeted', 'Целевой')], default='introductory', max_length=50, verbose_name='Категория'),
        ),
    ]
