# Generated by Django 3.2 on 2025-05-29 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20250529_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['-created_date'], 'verbose_name': 'Инструктаж', 'verbose_name_plural': 'Инструктажи'},
        ),
        migrations.AddField(
            model_name='instruction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
