# Generated by Django 3.2 on 2025-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20250529_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/instructions/', verbose_name='Файл'),
        ),
    ]
