# Generated by Django 3.2 on 2025-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
