# Generated by Django 3.2 on 2025-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20250529_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
    ]
