# Generated by Django 3.2 on 2025-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_instruction_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
