# Generated by Django 3.2 on 2025-05-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_instruction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='content',
        ),
    ]
