# Generated by Django 3.2 on 2025-05-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_remove_instruction_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
