# Generated by Django 3.2 on 2025-05-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_instruction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('main_laws', 'Основные законы и кодексы'), ('RLA', 'Нормативно-правовые акты (НПА)'), ('rules_and_requirements', 'Правила и требования по охране труда'), ('tech_standarts', 'Технические регламенты и стандарты'), ('changes_and_updates', 'Изменения и обновления'), ('letters', 'Письма и разъяснения госорганов')], max_length=50, verbose_name='Категория')),
                ('topics', models.CharField(blank=True, max_length=255, verbose_name='Темы')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/documents/', verbose_name='Файл')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
                ('valid_to', models.DateField(verbose_name='Дата окончания действия')),
            ],
            options={
                'verbose_name': 'Законодательство',
                'verbose_name_plural': 'Законодательства',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('construction', 'Строительство'), ('mining', 'Горная промышленность'), ('neftegas', 'Нефтегаз')], max_length=50, verbose_name='Категория')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучение',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speakers_profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='special',
            field=models.CharField(blank=True, choices=[('certificate', 'Сертификат'), ('live', 'Только в прямом эфире'), ('free', 'Бесплатно')], max_length=20, null=True, verbose_name='Специальное'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('recording', 'Сейчас идет'), ('scheduled', 'Ближайшие вебинары (анонс)'), ('completed', 'Прошедшие вебинары (архив)')], max_length=20, verbose_name='Статус'),
        ),
    ]
