# Generated by Django 3.2 on 2025-05-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20250530_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='duration',
            field=models.CharField(max_length=255, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='speakers_profession',
            field=models.CharField(max_length=255, verbose_name='Профессия'),
        ),
    ]
