# Generated by Django 3.2 on 2025-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20250530_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changed_user',
            field=models.JSONField(default=dict, verbose_name='Внесший изменения'),
        ),
    ]
