# Generated by Django 3.2 on 2025-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_article_changed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='changed_user',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Внесший изменения'),
        ),
    ]
