# Generated by Django 3.2 on 2025-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20250603_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
