# Generated by Django 3.2 on 2025-06-06 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_document_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_date'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
