# Generated by Django 3.2 on 2025-06-06 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['-created_date'], 'verbose_name': 'Законодательство', 'verbose_name_plural': 'Законодательства'},
        ),
        migrations.AddField(
            model_name='law',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
