# Generated by Django 3.2 on 2025-06-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиля пользователей'},
        ),
    ]
