# Generated by Django 3.2 on 2025-06-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftarticle',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Черновик новоости', 'verbose_name_plural': 'Черновики новостей'},
        ),
    ]
