# Generated by Django 3.2 on 2025-06-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_alter_draftarticle_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
