# Generated by Django 3.2 on 2025-06-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('is_private', models.BooleanField(default=False, help_text='Доступна только авторизованным пользователям', verbose_name='Внутренняя категория')),
            ],
            options={
                'verbose_name': 'Категория события',
                'verbose_name_plural': 'Категории событий',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('color', models.CharField(default='#FF0000', help_text='Цвет в HEX формате (например, #FF0000)', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег события',
                'verbose_name_plural': 'Теги событий',
            },
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
        migrations.AddField(
            model_name='event',
            name='author_avatar',
            field=models.ImageField(blank=True, upload_to='speakers/', verbose_name='Аватар спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя и фамилия спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveIntegerField(null=True, verbose_name='Длительность (часы)'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/', verbose_name='Обложка события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='news.EventCategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.EventTag', verbose_name='Теги'),
        ),
    ]
