# Generated by Django 3.2 on 2025-06-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20250613_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
