# Generated by Django 3.2 on 2025-06-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_auto_20250614_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
