# Generated by Django 3.2 on 2025-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20250614_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
