# Generated by Django 3.2 on 2025-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_instruction_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
