# Generated by Django 3.2 on 2025-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_instruction_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.JSONField(default=dict, verbose_name='Фото'),
        ),
    ]
