# Generated by Django 3.2 on 2025-06-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_faq_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.ImageField(default=dict, upload_to='', verbose_name='Фото'),
        ),
    ]
