# Generated by Django 3.2 on 2025-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_alter_faq_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
