# Generated by Django 3.2 on 2025-06-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_auto_20250615_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
    ]
