# Generated by Django 3.2 on 2025-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_remove_faq_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа'),
        ),
    ]
