# Generated by Django 3.2 on 2025-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_law_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
