# Generated by Django 3.2 on 2025-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_checklist_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='category',
            field=models.CharField(blank=True, choices=[('checklist_1', 'Чеклист 1'), ('checklist_2', 'Чеклист 2'), ('checklist_3', 'Чеклист 3'), ('checklist_4', 'Чеклист 4')], max_length=50, null=True, verbose_name='Категория'),
        ),
    ]
