# Generated by Django 3.2 on 2025-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_checklist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
