# Generated by Django 3.2 on 2025-06-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_checklist_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checkpoints',
        ),
    ]
