# Generated by Django 3.2 on 2025-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0048_remove_checklist_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
