# Generated by Django 3.2 on 2025-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0049_event_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.CharField(blank=True, choices=[('checklist_1', 'Обходы по Безопасности'), ('checklist_2', 'Проверочные листы оборудования'), ('checklist_3', 'Шаблоны расследований'), ('checklist_4', 'Отчетность')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('safety_management', 'Safety management'), ('incidents', 'Инциденты и расследования'), ('other', 'Другие документы')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='category',
            field=models.CharField(choices=[('introductory', 'Вводный'), ('primary_workplace', 'Первичный'), ('instructions', 'Инструкции по БиОТ')], default='introductory', max_length=50, verbose_name='Категория'),
        ),
    ]
