# Generated by Django 3.2 on 2025-06-15 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0050_auto_20250615_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
