# Generated by Django 3.2 on 2025-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0051_alter_checklist_valid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='url',
        ),
        migrations.AddField(
            model_name='checklist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/checklist/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/checklist/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='study',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='law',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/laws/', verbose_name='Файл'),
        ),
    ]
