# Generated by Django 3.2 on 2025-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0052_auto_20250616_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/checklist/', verbose_name='Фото или видео'),
        ),
        migrations.AlterField(
            model_name='study',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото или видео'),
        ),
    ]
