# Generated by Django 3.2 on 2025-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_auto_20250616_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, choices=[('organisation', 'Организация охраны труда'), ('PPE', 'СИЗ и рабочая форма'), ('documents', 'Документы и оформление'), ('inspections', 'Проверки и ответственность'), ('accidents', 'Несчастные случаи и расследования')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.CharField(choices=[('main_laws', 'Основные законы и кодексы'), ('RLA', 'Нормативно-правовые акты (НПА)'), ('rules_and_requirements', 'Правила и требования по охране труда'), ('tech_standarts', 'Технические регламенты и стандарты'), ('changes_and_updates', 'Изменения и обновления')], max_length=50, verbose_name='Категория'),
        ),
    ]
