# Generated by Django 3.2 on 2025-06-16 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_auto_20250616_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кейс автоматизации',
                'verbose_name_plural': 'Кейсы автоматизации',
                'ordering': ['-created_date'],
            },
        ),
    ]
