# Generated by Django 3.2 on 2025-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0056_riskmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmanagement',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/riskManagement/', verbose_name='Файл'),
        ),
    ]
