# Generated by Django 3.2 on 2025-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0057_auto_20250616_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcases',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
