# Generated by Django 3.2 on 2025-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0058_alter_automationcases_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcases',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
