# Generated by Django 3.2 on 2025-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0059_alter_automationcases_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='law',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
