# Generated by Django 3.2 on 2025-06-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0060_auto_20250617_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='pinned_to_main',
            field=models.BooleanField(default=False, verbose_name='Закрепить на главную'),
        ),
    ]
