# Generated by Django 3.2 on 2025-06-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0062_auto_20250622_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='news',
            new_name='article',
        ),
    ]
