# Generated by Django 3.2 on 2025-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0063_rename_news_articlecomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='author_avatar',
            field=models.ImageField(blank=True, upload_to='uploads/article/avatars/', verbose_name='Аватар эксперта'),
        ),
        migrations.CreateModel(
            name='LawComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author_full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя и фамилия эксперта')),
                ('author_avatar', models.ImageField(blank=True, upload_to='uploads/laws/avatars/', verbose_name='Аватар эксперта')),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.law', verbose_name='Законодательство')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
                'ordering': ['-created_at'],
            },
        ),
    ]
