# Generated by Django 3.2 on 2025-07-03 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0064_auto_20250622_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qauipmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
        ),
    ]
