# Generated by Django 3.2 on 2025-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0065_qauipmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='qauipmedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
