# Generated by Django 4.2.23 on 2025-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0071_automationcases_custom_new_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='custom_new_days',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано, переопределяет стандартные 7 дней', null=True, verbose_name='Период новизны (дней)'),
        ),
    ]
