# Generated by Django 4.2.23 on 2025-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0073_law_custom_new_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession', models.TextField(blank=True, null=True, verbose_name='Профессия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('article_count', models.IntegerField(default=0, verbose_name='Кол-во статей')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
