# Generated by Django 4.2.23 on 2025-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0074_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.JSONField(default=dict, verbose_name='Картинки'),
        ),
    ]
