# Generated by Django 4.2.23 on 2025-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0075_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='authors/', verbose_name='Фото автора'),
        ),
    ]
