# Generated by Django 4.2.23 on 2025-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0076_alter_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkedIn'),
        ),
        migrations.AddField(
            model_name='author',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
