# Generated by Django 4.2.23 on 2025-07-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0077_author_linkedin_url_author_whatsapp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
    ]
