# Generated by Django 4.2.23 on 2025-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0079_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Закрепить в календарь'),
        ),
    ]
