# Generated by Django 4.2.23 on 2025-07-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0081_rename_author_article_old_author_checklist_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='old_author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.author', verbose_name='Автор'),
        ),
    ]
