# Generated by Django 4.2.23 on 2025-08-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author'),
        ('news', '0082_remove_article_old_author_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='users.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='users.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.author', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
