# Generated by Django 5.2.13 on 2026-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0083_alter_article_author_alter_checklist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_kz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
    ]
