# Generated by Django 5.2.13 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0085_copy_article_text_to_ru_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='author_full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='author_full_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='author_full_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='company_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='company_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='company_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='automationcases',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='category',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_en',
            field=models.CharField(max_length=250, null=True, verbose_name='СЕО заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='СЕО заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='СЕО заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='use_case_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Сценарий использования'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='use_case_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Сценарий использования'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='use_case_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Сценарий использования'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_kz',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='document',
            name='topics_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='content_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='title_kz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='draftarticle',
            name='title_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_full_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_full_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_job_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_job_title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='author_job_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность спикера'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_kz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='name_kz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_profession_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия автора'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_profession_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия автора'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_profession_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия автора'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='fixedmenu',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='fixedmenu',
            name='name_kz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='fixedmenu',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='author_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструктажа'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструктажа'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название инструктажа'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='law',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='law',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='law',
            name='topics_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='law',
            name='topics_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='law',
            name='topics_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='author_full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='author_full_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='author_full_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя и фамилия эксперта'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='text_kz',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='lawcomment',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='summary_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='summary_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='legalact',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='qauipmedia',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='qauipmedia',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='qauipmedia',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='study',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='study',
            name='description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='study',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='study',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='study',
            name='title_kz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='study',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_kz',
            field=models.TextField(null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Лид'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_tag_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Описание для сео'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_tag_kz',
            field=models.CharField(max_length=80, null=True, verbose_name='Описание для сео'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_tag_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Описание для сео'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name_kz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название тега'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_kz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
