# Generated by Django 5.2.13 on 2026-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0086_multilingual_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name_kz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название источника'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Источник'),
        ),
    ]
