# Generated by Django 5.2.13 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
