# Generated by Django 5.2.13 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='content_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source_kz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='source_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='title_kz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
